import os
nombre_essais = 10
mot = input("Choisis le mot à deviner: ")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
liste_choix = list(mot)
lettres_trouvees = []
lettres_manquantes = liste_choix.copy()
while True:
    choix_j2 = input("Une lettre: ")
    if choix_j2 in liste_choix:
        print("oui")
        lettres_trouvees.append(choix_j2)
        lettres_manquantes.remove(choix_j2)
        print("Lettres trouvées :", " ".join([lettre if lettre in lettres_trouvees else "_" for lettre in liste_choix]))
        if not lettres_manquantes:
            print("Bravo, vous avez gagné !")

    else:
        print("Non")
        nombre_essais = nombre_essais - 1
        print("Il vous reste " + str(nombre_essais) + " essais")
        print("Lettres trouvées :", " ".join([lettre if lettre in lettres_trouvees else "_" for lettre in liste_choix]))
        if nombre_essais == 0:
            print("Perdu !")
            break